### ISSUE TITLE
some questions associated with change to individual-level local community 

### ISSUE THREAD

**Issue by jidec** [role-model/roleR#13]
1. In the speciation method in the roleModel object, the probability of a species being selected is the metaComm abundance weighted by dispersal probability + local comm abundance weighted by birth probability. Naturally those vectors have to be of equal length so must be both either species or individuals. Should we keep this speciation function as taking a species index, or should we revise it to take an individual? But if we are picking an individual, I am not sure how metacomm abundance weighting would work.

2. Should we keep species abundances, and also possibly mean species traits saved? These would otherwise have to be recalculated in roleModel death to check for species extinctions and in speciation as mentioned in 1. It would likely be less expensive to keep these saved than to recalculate every loop. 

3. I am trying to vectorize competitive filtering to avoid awful double for loops. Is it OK if the mean is calculated within the
exponent, if that makes sense? I believe that might look like:

```
// traitdiffs contains i - j in all indices (i,j)
// requires looping thru every individual once
NumericVector c_probs = NumericVector(localComm.Imax);

for(int i = 0; i < localComm.Imax; i++) {
    c_probs[i] = 1 - exp(-1/sigma_e * pow(mean(localComm.traitdiffs(i,_)), 2)); // traitdiffs(i_) is equivalent to traitdiffs[i, ] in R
}
```

Please feel free to reply with any feedback! -Jacob

**Comment by ajrominger** [comment]
Great questions!  Here are some thoughts:

1. This could be a work-around that would mean we don't need to have equal length species abundance vectors: we re-order the simulation algo to 
    - let an individual die
    - then first figure out immigration or local birth
    - replace the death with either the immigrant or local birth individual (keeping track of its species ID)
    - then figure out if that species underwent "point mutation" type speciation
this is actually the way that Hubbell (and others following him) first implemented the UNTB so it's perfectly valid
2. Let's discuss more if we need to track local species abundances and mean traits during each iteration of the loop; my initial thought is that perhaps we don't need to (at each iteration of the loop) in which case we can save this computation for only the few times we need to (basically during any potential periodic output of simulation results and at the end of the simulation run)
3. let's talk more about the calculation of the mean in environmental filtering.  Based on eq 2 from [Luiselli et al.](https://www.biorxiv.org/content/biorxiv/early/2021/05/11/2021.05.11.442553.full.pdf) I think there's no need to take a mean in the calculation of env filtering death probs

**Comment by jidec** [comment]
Based on Andy and I's Zoom, here are some outcomes:

1. We will be revising the core loop structure per Andy's comment to avoid the need to calculate weighted probability of whether species comes from local birth or metacommunity
2. We will be keeping track of species abundances just to minimize computation during the loop, particularly of checking all individuals to see which species are extinct (have no individuals left) 
3. We went over how to code the competitive filtering computation, which in pseudocode looks like:
      c_probs = 1/J * rowSums(exp((-1/params.values.sigma_c) * pow(traitdiffs, 2));
Where J is the number of individuals in the local community and traitdiffs is a J*J matrix containing the cross difference of the traits vector containing the traits of individuals
