### ISSUE TITLE
Model memory overhead failing for large(ish) models

### ISSUE THREAD

**Issue by connor-french** [role-model/roleR#25]
Although I’m encountering this problem in `roleShiny`, it seems to be a `roleR` and `IterModelCpp` problem. If I run a model with enough individuals, species, migration, etc. (reprex below), I get the error in the image. The models use a ton of memory (my R memory usage and RAM balloons to ~10-15 GB during a model run before either failing or retaining a large model object). 

Here is a set of parameters that reproduces the problem on my machine. Memory ballooned to ~14.5 GB when running. The error message is simpler when just running `roleR` outside of `roleShiny`: `Error: vector memory exhausted (limit reached?)` but I'm leaving the `roleShiny` error because it contains more info. 

```#### error reprex ####
params <- untbParams(
  individuals_local = 900,
  individuals_meta = 9000,
  species_meta = 900,
  speciation = 0.3,
  dispersal_prob = 0.5,
  init_type = "oceanic_island",
  niter = 9000,
  niterTimestep = 10
)


exp <- roleModel(params)

m <- iterModel(exp)
```

Maybe this is an unreasonable model specification, but it's at least a view of the upper limit of what the function can handle.

![5E55D616-53E0-4310-8ADB-9C3CB7583F45](https://user-images.githubusercontent.com/37662997/204111449-31c29175-2ef8-41b8-b533-c55ed548ba66.png)

**Comment by jidec** [comment]
Thanks for noting this Connor - this was caused by the initial buffering of the phylo object accept new species without reallocating, which was happening WAY, WAY too much.
