### ISSUE TITLE
Package checks

### ISSUE THREAD

**Issue by diazrenata** [role-model/roleR#62]
- [ ] R CMD Check
- [ ] CI tests
- [ ] CI test coverage

**Comment by ajrominger** [comment]
Clean up documentation so the only things exported are what we really want exported.  This means:
- only very intentionally exporting rcpp things (default should be nothing exported)
- figure out what `sp1_gr` is and why it's exported
- figure out why `exportPattern("^[[:alpha:]]+")` is in namespace
- figure out do `$` and `[` need to be in exports if what we're doing is defining new methods for these generics 

We also need to make sure all arguments are documented in `./man/` files

**Comment by diazrenata** [comment]
Outstanding warnings:

- [ ] `data` contains no datasets --> remove data
- [ ] numerous undocumented code objects --> add docs, this will be tedious but straightforward
- [ ] contents of `data` directory --> could use `inst`
- [ ] rlang imports in tests --> currently just commenting out problematic tests, will want to sleuth more here later

**Comment by ajrominger** [comment]
@diazrenata it seems like a lot of the undocumented things boil down to just an issue with file order.  for example, documenting `getFinalState` gives a warning that `roleModel` and `roleExperiment` are undefined. but they *are* defined, it's just that they're defined in a file that alphabetically comes after the file where `getFinalState` is defined.  the solution (short of renaming the files) is to use the `@include` roxygen tag.

so, for example, the file defining `getFinalState` will need to include this in the roxygen "preamble":

```
#' @include roleModel.R roleExperiment.R
```
