### ISSUE TITLE
roleExperiment.R `setAs` - attempt to replicate an object of type 'closure'

### ISSUE THREAD

**Issue by isaacovercast** [role-model/roleR#86]
I am pretty sure this is a downstream result of the iterFun implementation.

If I do this `as(model, "roleExperiment")`, I get this:
```
Error in rep(p, length(j)): attempt to replicate an object of type 'closure'
Traceback:

1. as(model, "roleExperiment")
2. asMethod(object)
3. lapply(pnames, function(p) {
 .     p <- slot(from@params, p)
 .     if (length(p) > 1) {
 .         p <- c(p[1], p)
 .         return(p[j])
 .     }
 .     else {
 .         return(rep(p, length(j)))
 .     }
 . })
4. FUN(X[[i]], ...)
```
Looks like this is coming from roleExperiment.R:114. Here if 'p' is a function (like with iterFuns) then the call to `rep(p, #)` will complain and error out.

**Comment by ajrominger** [comment]
once #77 is merged this will indeed be resolved
